repos:
  - repo: https://github.com/hyperrealm/autopep8
    rev: v1.6.0
    hooks:
      - id: autopep8
        args: [--in-place, --aggressive, --aggressive, --max-line-length=120]
        language_version: python3